//
//  Icons.swift
//  tachiyomi
//
//  Created by Grace, Mu-Hui Yu on 8/3/23.
//

import UIKit

class Icons {
    static var square: String { "square" }
    static var squareFill: String { "square.fill" }
    static var arrowUp: String { "arrow.up" }
    static var arrowDown: String { "arrow.down" }
    static var arrowUpCircle: String { "arrow.up.circle" }
    static var arrowDownCircle: String { "arrow.down.circle" }
    static var arrowTriangleUp: String { "arrow.triangle.up" }
    static var arrowTriangleDown: String { "arrow.triangle.down" }
    static var transfer: String { "arrow.2.squarepath" }
    static var photoFill: String { "photo.fill" }
    static var lightbulb: String { "lightbulb" }
    static var dollarsignCircle: String { "dollarsign.circle" }
    static var dollarsignCircleFill: String { "dollarsign.circle.fill" }
    static var dollarSignArrowCirclePath: String { "dollarsign.arrow.circlepath" }
    static var plus: String { "plus" }
    static var eyeglasses: String { "eyeglasses" }
    static var globe: String { "globe" }
    static var sparkle: String { "sparkle" }
    static var sparkles: String { "sparkles" }
    static var cursorarrowRays: String { "cursorarrow.rays" }
    static var handsSparkles: String { "hands.sparkles" }
    static var handsSparklesFill: String { "hands.sparkles.fill" }
    static var plusCircle: String { "plus.circle" }
    static var plusCircleFill: String { "plus.circle.fill" }
    static var house: String { "house" }
    static var houseFill: String { "house.fill" }
    static var bedDouble: String { "bed.double" }
    static var bedDoubleFill: String { "bed.double.fill" }
    static var creditcard: String { "creditcard" }
    static var creditcardFill: String { "creditcard.fill" }
    static var creditcardCircle: String { "creditcard.circle" }
    static var creditcardCircleFill: String { "creditcard.circle.fill" }
    static var banknote: String { "banknote" }
    static var pencil: String { "pencil" }
    static var cart: String { "cart" }
    static var cartFill: String { "cart.fill" }
    static var giftcard: String { "giftcard" }
    static var checkmark: String { "checkmark" }
    static var pause: String { "pause" }
    static var pauseFill: String { "pause.fill" }
    static var pauseCircle: String { "pause.circle" }
    static var pauseCircleFill: String { "pause.circle.fill" }
    static var questionmark: String { "questionmark" }
    static var questionmarkCircle: String { "questionmark.circle" }
    static var person: String { "person" }
    static var personFill: String { "person.fill" }
    static var plusminus: String { "plusminus" }
    static var plusminusFill: String { "plusminus.fill" }
    static var plusminusCircle: String { "plusminus.circle" }
    static var clock: String { "clock" }
    static var clockFill: String { "clock.fill" }
    static var gearshape: String { "gearshape" }
    static var gearshapeFill: String { "gearshape.fill" }
    static var calender: String { "calendar" }
    static var calenderBadgePlus: String { "calendar.badge.plus" }
    static var calenderBadgeMinus: String { "calendar.badge.minus" }
    static var calenderBadgeClock: String { "calendar.badge.clock" }
    static var bell: String { "bell" }
    static var bellFill: String { "bell.fill" }
    static var bellbadge: String { "bell.badge" }
    static var bellbadgeFill: String { "bell.badge.fill" }
    static var tag: String { "tag" }
    static var tagFill: String { "tag.fill" }
    static var xmark: String { "xmark" }
    static var hammerFill: String { "hammer.fill" }
    static var forkKnife: String { "fork.knife" }
    static var cupAndSaucerFill: String { "cup.and.saucer.fill" }
    static var takeoutbagAndCupAndStraw: String { "takeoutbag.and.cup.and.straw" }
    static var takeoutbagAndCupAndStrawFill: String { "takeoutbag.and.cup.and.straw.fill" }
    static var boltFill: String { "bolt.fill" }
    static var boltCircle: String { "bolt.circle" }
    static var boltCircleFill: String { "bolt.circle.fill" }
    static var wifi: String { "wifi" }
    static var dropFill: String { "drop.fill" }
    static var iphoneHomeButton: String { "iphone.homebutton" }
    static var tvFill: String { "tv.fill" }
    static var bus: String { "bus" }
    static var carFill: String { "car.fill" }
    static var paperclip: String { "paperclip" }
    static var gift: String { "gift.fill" }
    static var externalDriveFill: String { "externaldrive.fill" }
    static var appleLogo: String { "applelogo" }
    static var terminal: String { "terminal" }
    static var terminalFill: String { "terminal.fill" }
    static var network: String { "network" }
    static var graduationCapFill: String { "graduationcap.fill" }
    static var airplane: String { "airplane" }
    static var tramFill: String { "tram.fill" }
    static var mapFill: String { "map.fill" }
    static var pillsFill: String { "pills.fill" }
    static var crossCaseFill: String { "cross.case.fill" }
    static var eyeFill: String { "eye.fill" }
    static var mouth: String { "mouth" }
    static var eyebrow: String { "eyebrow" }
    static var mouthFill: String { "mouth.fill" }
    static var filmFill: String { "film.fill" }
    static var ticketFill: String { "ticket.fill" }
    static var playTvFill: String { "play.tv.fill" }
    static var noteText: String { "note.text" }
    static var gamecontrollerFill: String { "gamecontroller.fill" }
    static var figureWalk: String { "figure.walk" }
    static var tshirtFill: String { "tshirt.fill" }
    static var shippingBoxFill: String { "shippingbox.fill" }
    static var scrollFill: String { "scroll.fill" }
    static var characterBubbleFill: String { "character.bubble.fill" }
    static var textBookClosedFill: String { "text.book.closed.fill" }
    static var crossFill: String { "cross.fill" }
    static var heartFill: String { "heart.fill" }
    static var chevronForward: String { "chevron.forward" }
    static var chevronForwardCircle: String { "chevron.forward.circle" }
    static var chevronForwardCircleFill: String { "chevron.forward.circle.fill" }
    static var chevronBackward: String { "chevron.backward" }
    static var chevronBackwardCircle: String { "chevron.backward.circle" }
    static var chevronBackwardCircleFill: String { "chevron.backward.circle.fill" }
    static var chevronUp: String { "chevron.up" }
    static var chevronDown: String { "chevron.down" }
    static var chartBar: String { "chart.bar" }
    static var chartBarFill: String { "chart.bar.fill" }
    static var magnifyingglass: String { "magnifyingglass" }
    static var squareGrid2x2: String { "square.grid.2x2" }
    static var textAlignleft: String { "text.alignleft" }
    static var textAlignright: String { "text.alignright" }
    static var squareOnSquare: String { "square.on.square" }
    static var rectangleOnRectangle: String { "rectangle.on.rectangle" }
    static var bookClosed: String { "book.closed" }
    static var bookClosedFill: String { "book.closed.fill" }
    static var book: String { "book" }
    static var bookFill: String { "book.fill" }
    static var clockArrowCirclepath: String { "clock.arrow.circlepath" }
    static var exclamationmarkCircle: String { "exclamationmark.circle" }
    static var exclamationmarkCircleFill: String { "exclamationmark.circle.fill" }
    static var safari: String { "safari" }
    static var safariFill: String { "safari.fill" }
    static var ellipsis: String { "ellipsis" }
    static var line3HorizontalDecrease: String { "line.3.horizontal.decrease" }
}
